name: test

on:
  pull_request_target: {}

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read

jobs:
    job:
      runs-on: ubuntu-22.04
      steps:
        - name: Getting image tag
          id: tag
          run: |
            if [ "${{ github.event.pull_request.head.sha }}" != "" ]; then
              tag=${{ github.event.pull_request.head.sha }}
            else
              tag=${{ github.sha }}
            fi
            echo tag=${tag} >> $GITHUB_OUTPUT
        - name: Checkout default branch (trusted)
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            ref: ${{ github.event.repository.default_branch }}
            persist-credentials: false
        - name: use secure action
          uses: ./.github/actions/secure-action
        # Warning: since this is a privileged workflow, subsequent workflow job
        # steps must take care not to execute untrusted code.
        - name: Checkout pull request branch (NOT TRUSTED)
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            persist-credentials: false
            ref: ${{ steps.tag.outputs.tag }}
        - name: use secure action
          uses: ./.github/actions/secure-action
