name: test

# Any change in triggers needs to be reflected in the concurrency group.
on:
  pull_request: {}

permissions: read-all

jobs:
    job:
      runs-on: ubuntu-20.04
      steps:
        - name: use a secret
          run: |
            echo ${{ secrets.TEST }} > file
        - name: Setup tmate session
          uses: mxschmitt/action-tmate@v3